#!/usr/bin/env bash
# configure web-02 to be identical to web-01

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 431699-web-01 34.227.89.197 check
   server 431699-web-02 100.25.20.169 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
